name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y sqlite3 libvips

      - name: Set up database
        run: bin/rails db:test:prepare

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rspec

      - name: Upload screenshots for failed tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
